#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#Cartas
cartas:
  path: /cartas
  controller: App\Controller\CartasController::cartas
  methods: GET


#Monstruos
monstruos:
  path: /monstruos
  controller: App\Controller\MonstruosController::monstruos
  methods: GET


#Magicas
magicas:
  path: /magicas
  controller: App\Controller\MagicasController::magicas
  methods: GET


#Trampas
trampas:
  path: /trampas
  controller: App\Controller\TrampasController::trampas
  methods: GET


#Decks
decks:
  path: /decks
  controller: App\Controller\DecksController::decks
  methods: GET|POST

deckById:
  path: /deck/{id}
  controller: App\Controller\DecksController::deckById
  methods: GET|PUT|DELETE

decksByUser:
  path: /usuario/{id}/decks
  controller: App\Controller\DecksController::decksByUser
  methods: GET

verCartasEnDecks:
  path: /deck/{deck_id}/cartas
  controller: App\Controller\DecksController::cartaEnDeck
  methods: GET

anyadirCartasEnDecks:
  path: /deck/{deck_id}
  controller: App\Controller\DecksController::addCartaToDeck
  methods: PUT

borrarCartasEnDecks:
  path: /deck/{deck_id}/carta/{carta_id}
  controller: App\Controller\DecksController::removeCartaFromDeck
  methods: DELETE


#Usuarios
usuarios:
  path: /usuarios
  controller: App\Controller\UsuariosController::usuarios
  methods: GET|POST

usuarioById:
  path: /usuario/{id}
  controller: App\Controller\UsuariosController::usuarioById
  methods: GET|PUT|DELETE
