#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#Cartas
cartas:
  path: /cartas
  controller: App\Controller\CartasController::cartas
  methods: GET


#Monstruos
monstruos:
  path: /monstruos
  controller: App\Controller\MonstruosController::monstruos
  methods: GET


#Magicas
magicas:
  path: /magicas
  controller: App\Controller\MagicasController::magicas
  methods: GET

#Trampas
trampas:
  path: /trampas
  controller: App\Controller\TrampasController::trampas
  methods: GET

