<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN7BOV2E\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN7BOV2E/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN7BOV2E.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN7BOV2E\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN7BOV2E\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N7BOV2E',
    'container.build_id' => '80705903',
    'container.build_time' => 1714321698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN7BOV2E');
