<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI0FxHOI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI0FxHOI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI0FxHOI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI0FxHOI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI0FxHOI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I0FxHOI',
    'container.build_id' => '99f683e7',
    'container.build_time' => 1715793412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI0FxHOI');
