<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRKQp2mt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRKQp2mt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRKQp2mt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRKQp2mt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRKQp2mt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RKQp2mt',
    'container.build_id' => '536d3010',
    'container.build_time' => 1714250689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRKQp2mt');
